services:
  hasktorch:
    build: .
    volumes:
      - .:/home/ubuntu/neuralWani
      - ~/.ssh/id_rsa:/home/ubuntu/.ssh/id_rsa
    ports:
      - "8888:8888"
    command: jupyter lab --ip 0.0.0.0 --NotebookApp.token=''
