name: neuralWani
version: 0.1.0.0
github: "miyagawananako/neuralWani"
license: BSD-3-Clause
author: Nanako Miyagawa
maintainer: Nanako Miyagawa
copyright: Nanako Miyagawa

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at https://github.com/miyagawananako/neuralWani#readme

dependencies:
  - base >= 4.7 && < 5
  - lightblue >= 0.3
  - store
  - bytestring
  - list-t
  - hasktorch >= 0.2
  - hasktorch-tools
  - text
  - containers
  - nlp-tools
  - random-shuffle
  - cereal-text
  - time
  - random
  - directory
  - filepath
  - split
  - parserModules
  - array >= 0.5.3.0 # Alexが必要
  - mtl >= 2.2.2 # Except モナド用
  - data-default
  - jsem >= 1.1
  - deepseq

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src
  build-tools:
    - alex # Lexer.x のビルドに必要
    - happy # Parser.y のビルドに必要

executables:
  train-exe:
    main: Main.hs
    source-dirs: app/train
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - neuralWani

  builder-exe:
    main: Main.hs
    source-dirs: app/builder
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - neuralWani

  evaluate-exe:
    main: Main.hs
    source-dirs: app/evaluate
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - neuralWani

tests:
  test:
    main: Main.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - neuralWani
