resolver: lts-20.26

flags: {}

extra-include-dirs:
  - /home/ubuntu/libraries/hasktorch/deps/libtorch/include/torch/csrc/api/include
  - /home/ubuntu/libraries/hasktorch/deps/libtorch/include

extra-lib-dirs:
  - /home/ubuntu/libraries/hasktorch/deps/libtorch/lib
  - /home/ubuntu/libraries/hasktorch/deps/mklml/lib
  - /home/ubuntu/libraries/hasktorch/deps/libtokenizers/lib

extra-deps:
  - git: http://github.com/DaisukeBekki/JSeM.git
    commit: c2cd39168e267007b4690dbf625329bac57a8185
  - git: git@github.com:miyagawananako/lightblue.git
    commit: f07d3dbfac4b807f7985d060b91dcd5119241e64
  - git: git@github.com:hinarid/waniTest.git
    commit: 1fbc5e13f29c9b4b823c42cae15e853dc0b79b3b
# for hasktorch
  - /home/ubuntu/libraries/hasktorch/codegen
  - /home/ubuntu/libraries/hasktorch/libtorch-ffi
  - /home/ubuntu/libraries/hasktorch/libtorch-ffi-helper
  - /home/ubuntu/libraries/hasktorch/hasktorch
  - datasets-0.4.0@sha256:9bfd5b54c6c5e1e72384a890cf29bf85a02007e0a31c98753f7d225be3c7fa6a,4929
  - require-0.4.10@sha256:41b096daaca0d6be49239add1149af9f34c84640d09a7ffa9b45c55f089b5dac,3759
  - indexed-extras-0.2@sha256:e7e498023e33016fe45467dfee3c1379862e7e6654a806a965958fa1adc00304,1349
  - normaldistribution-1.1.0.3@sha256:2615b784c4112cbf6ffa0e2b55b76790290a9b9dff18a05d8c89aa374b213477,2160
  - term-rewriting-0.4.0.2@sha256:5412f6aa29c5756634ee30e8df923c83ab9f012a4b8797c460af3d7078466764,2740
  - git: https://github.com/hasktorch/tintin
    commit: 0d5afba586da01e0a54e598745676c5c56189178
  - git: https://github.com/hasktorch/tokenizers
    commit: 9d25f0ba303193e97f8b22b9c93cbc84725886c3
    subdirs:
    - bindings/haskell/tokenizers-haskell
  - git: https://github.com/hasktorch/typelevel-rewrite-rules
    commit: 4176e10d4de2d1310506c0fcf6a74956d81d59b6
  - git: https://github.com/hasktorch/type-errors-pretty
    commit: 32d7abec6a21c42a5f960d7f4133d604e8be79ec
  - union-find-array-0.1.0.3@sha256:242e066ec516d61f262947e5794edc7bbc11fd538a0415c03ac0c01b028cfa8a,1372
  - clay-0.14.0@sha256:382eced24317f9ed0f7a0a4789cdfc6fc8dd32895cdb0c4ea50a1613bee08af3,2128
  - inline-c-0.9.1.10
  - inline-c-cpp-0.5.0.2
  - git: http://github.com/DaisukeBekki/nlp-tools
    commit: e4bd3783f4e872b8df29538d9219e41f40378363
  - git: http://github.com/DaisukeBekki/hasktorch-tools.git
    commit: 020a3d6cc02dc64e18db7219d343e8473f880a91
# for hasktorch-nlp-introduction
  - jsonl-0.2.0.0@sha256:35f8a3816f0b93830008709a8e64c0c69b9bc632a92c54b3be3345bfccba4a5c,1465

build:
  haddock: false
  haddock-arguments:
    haddock-args:
    - --odir=haddock
  open-haddocks: false
  haddock-internal: false
  haddock-hyperlink-source: true
